# Generated by Django 4.2.24 on 2025-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
    ]
