# Generated by Django 4.2.24 on 2025-09-19 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0002_article_cover_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-approved_at", "-created_at"),
                "permissions": [("can_approve", "Can approve articles")],
            },
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="user",
            name="published_articles",
            field=models.ManyToManyField(
                blank=True, related_name="independent_authors", to="newsroom.article"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscriptions_to_journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "JOURNALIST"},
                related_name="reader_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscriptions_to_publishers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_readers", to="newsroom.publisher"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "approved_at"], name="newsroom_ar_status_c011c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["publisher", "status"], name="newsroom_ar_publish_a7b076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "status"], name="newsroom_ar_author__2efa97_idx"
            ),
        ),
    ]
